import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image';
import profilePic from "../../public/images/profile/prajwal.png";
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout className='pt-0'>
          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="Prajwal" className="h-full w-full"/>
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Hi, I am Prajwal Upreti !" className='text-5xl'/>
              <AnimatedText text="Coding my way through pixels and dreams." className='text-4xl font-semibold'/>
              <p className='my-4 text-base font-medium'>
                As a web developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in web development.
              </p>
              <div className='flex items-center self-start mt-2'>
              <Link href="/dummy.pdf" target={'_blank'} 
              className='flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg font-semibold
              hover:bg-light hover:text-dark border border-solid border-transparent
              hover:border-dark' download={true}>
                Download Resume <LinkArrow className={"w-3 ml-1"} /></Link>
              <Link href="mailto:prazolupreti@gmail.com" target={'_blank'} 
              className='ml-4 flex items-center bg-dark text-light p-2 px-8 rounded-lg text-lg font-semibold 
              hover:bg-light hover:text-dark border border-solid border-transparent
              hover:border-dark'>
                Email Me</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 '>
          <Image src={lightBulb} alt='Prajwal' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
